Controllers/FilmController.cs
using csharp_boolflix.Models;
using csharp_boolflix.Models.Form;
using csharp_boolflix.Models.Repository.Interfacce;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace csharp_boolflix.Controllers
{
    [Authorize]
    public class FilmController : Controller
    {
        IFilmRepository filmRepository;

        ICategoryRepository categoryRepository;

        IActorRepository actorRepository;

        public FilmController(IFilmRepository _filmRepository, ICategoryRepository _categoryRepository, IActorRepository _actorRepository)
        {
            filmRepository = _filmRepository;
            categoryRepository = _categoryRepository;
            actorRepository = _actorRepository;
        }

        public IActionResult Index()
        {
            List<Film> filmList = filmRepository.All();
            return View(filmList);
        }

        public IActionResult Create()
        {
            MediaForm formData = new MediaForm();
            formData.Categories = new List<SelectListItem>();
            formData.Actors = new List<SelectListItem>();

            filmRepository.AddFilmRelations(formData);

            return View(formData);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(MediaForm formData)
        {
            if (!ModelState.IsValid)
            {
                    formData.Categories = new List<SelectListItem>();

                    filmRepository.AddFilmRelations(formData);



                return View();
            }

            filmRepository.Create(formData.Film, formData.SelectedCategories, formData.SelectedActors);
            return RedirectToAction("Index", "Admin");
        }

        public IActionResult Detail(int id)
        {
            Film film = filmRepository.GetById(id);
            return View(film);
        }

        public IActionResult Update(int id)
        {
            Film film = filmRepository.GetById(id);

            MediaForm formData = new MediaForm();
            formData.Film = film;
            formData.Categories = new List<SelectListItem>();
            formData.Actors = new List<SelectListItem>();

            filmRepository.AddFilmRelations(formData, film);

            
            return View(formData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, MediaForm formData)
        {
            if (!ModelState.IsValid)
            {
                formData.Film.Id = id;
                formData.Categories = new List<SelectListItem>();
                formData.Actors = new List<SelectListItem>();

                filmRepository.AddFilmRelations(formData);

                return View(formData);
            }

            Film filmItem = filmRepository.GetById(id);

            filmRepository.Update(filmItem, formData.Film, formData.SelectedCategories, formData.SelectedActors);


            return RedirectToAction("Index", "Admin");
        }
    }


   
}

Controllers/TvShowController.cs
using csharp_boolflix.Models.Repository.Interfacce;
using csharp_boolflix.Models;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class TvShowController : Controller
    {
        ITvShowRepository tvShowRepository;

        public TvShowController(ITvShowRepository _tvShowRepository)
        {
            tvShowRepository = _tvShowRepository;
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TvShow tvShow)
        {
            if (!ModelState.IsValid)
                return View();

            tvShowRepository.Create(tvShow);
            return RedirectToAction("Index");
        }
    }
}

Views/Admin/Index.cshtml
@using csharp_boolflix.Models.Form
@model MediaForm

 <div class="container">
        <div class="row justify-content-between">
            @if (Model.Films.Count == 0 && Model.TvShows.Count == 0)
            {
                <h1>Non ci sono Contenuti al momento</h1>

            }

            else
            {
                @foreach (Film film in Model.Films)
                {
                    <div class="card col-3" style="width: 18rem;">
                        <img class="card-img-top" style="height: 200px;" src="@film.Image" alt="Card image cap">
                        <div class="card-body">
                            <h1>@film.Title</h1>
                            <p class="card-text">@film.Description</p>
                            <h5 class="card-title">@film.Duration</h5>
                            <span>@film.ReleaseDate.ToString("dd/MM/yyyy")</span>
                            <a
                                asp-controller="Film"
                                asp-action="Detail"
                                asp-route-id="@film.Id"
                                class="btn btn-primary my-5">visualizza Film
                            </a>    
                        </div>
                    </div>        
                }
                @foreach (TvShow tvShow in Model.TvShows)
                {
                    <div class="card col-3" style="width: 18rem;">
                        <img class="card-img-top" style="height: 200px;" src="@tvShow.Image" alt="Card image cap">
                        <div class="card-body">
                            <h1>@tvShow.Title</h1>
                            <p class="card-text">@tvShow.Description</p>
                                
                            <span>@tvShow.ReleaseDate.ToString("dd/MM/yyyy")</span>
                        </div>
                    </div>        
                }
            }
            <a
                asp-controller="Film"
                asp-action="Create"
                

                class="btn btn-primary my-5">Crea Film
            </a>
            <a
                asp-controller="TvShow"
                asp-action="Create"


                class="btn btn-success">Crea SerieTv
            </a>
        </div>
</div>